#!/bin/bash

[[ $1 == "--debug" ]] || [[ $1 == "-d" ]] && . hue_debug
. hue_settings

connection_test

while read -p "Please input color-themperature in mired from 153 (=cold) to 500 (=warm): " x
do
	if [[ ${x} -ge 153 ]] && [[ ${x} -le 500 ]]
	then
		w="$(printf '%04x' "${x}")"
		c="0x"${w:0:2}
		t="0x"${w:2}
		break
	else
		echo "Value out of range."
		continue
	fi
done

echo ${w}
echo $t", "$c

for lamp in ${array_lamps[@]}
do
	dbus-send --print-reply --system --dest=org.bluez /org/bluez/hci0/dev_${lamp}/service0023/char002c org.bluez.GattCharacteristic1.WriteValue array:byte:"${t}, ${c}" dict:string:variant:
done

[[ $1 == "--debug" ]] || [[ $1 == "-d" ]] && characteristic_values

