#!/bin/bash

[[ $1 == "--debug" ]] || [[ $1 == "-d" ]] && . hue_debug
. hue_settings

connection_test

while read -p "on/off : " x
do
	case "${x}" in
		on)
			y="0x01"
			break
			;;
		off)
			y="0x00"	
			break
			;;
		*)
			echo "Please just input on or off."
			;;
	esac
done

for lamp in ${array_lamps[@]}
do
	dbus-send --print-reply --system --dest=org.bluez /org/bluez/hci0/dev_${lamp}/service0023/char0026 org.bluez.GattCharacteristic1.WriteValue array:byte:"${y}" dict:string:variant:
done

[[ $1 == "--debug" ]] || [[ $1 == "-d" ]] && characteristic_values
