#!/bin/bash

. hue_settings

characteristic_values() {

	echo -e '\n'
	echo "######################################"
	echo ">>>>>> Manufacturer Name String <<<<<<"
	echo "######################################"
	echo "/service000a/char000b"
	for lamp in ${array_lamps[@]}
	do
		dbus-send --print-reply --system --dest=org.bluez /org/bluez/hci0/dev_${lamp}/service000a/char000b org.bluez.GattCharacteristic1.ReadValue dict:string:variant:
	done
	echo -e '\n'
	echo "######################################"
	echo ">>>>>>> Model Number String <<<<<<<<< "
	echo "######################################"
	echo "/service000a/char000d"
	for lamp in ${array_lamps[@]}
	do
		dbus-send --print-reply --system --dest=org.bluez /org/bluez/hci0/dev_${lamp}/service000a/char000d org.bluez.GattCharacteristic1.ReadValue dict:string:variant:
	done
	echo -e '\n'
	echo "######################################"
	echo ">>>>> Software Revision String <<<<<<<"
	echo "######################################"
	echo "/service000a/char000f"
	for lamp in ${array_lamps[@]}
	do
		dbus-send --print-reply --system --dest=org.bluez /org/bluez/hci0/dev_${lamp}/service000a/char000f org.bluez.GattCharacteristic1.ReadValue dict:string:variant:
	done
	echo -e '\n'
	echo "######################################"
	echo ">>>>>>>>> Lamp Name, alias <<<<<<<<<<<"
	echo "######################################"
	echo "/service0011/char0014"
	for lamp in ${array_lamps[@]}
	do
		dbus-send --print-reply --system --dest=org.bluez /org/bluez/hci0/dev_${lamp}/service0011/char0014 org.bluez.GattCharacteristic1.ReadValue dict:string:variant:
	done
	echo -e '\n'
	echo "########################################################################################"
	echo "> i guess Pairable state after AC-ON. After AC-ON the value changes to 02 for a while. <"
	echo "########################################################################################"
	echo "/service0011/char001b"
	for lamp in ${array_lamps[@]}
	do
		dbus-send --print-reply --system --dest=org.bluez /org/bluez/hci0/dev_${lamp}/service0011/char001b org.bluez.GattCharacteristic1.ReadValue dict:string:variant:
	done
	echo -e '\n'
	echo "######################################"
	echo ">>>>>>> read posible but ??? <<<<<<<<<"
	echo "######################################"
	echo "/service0023/char0024"
	for lamp in ${array_lamps[@]}
	do
		dbus-send --print-reply --system --dest=org.bluez /org/bluez/hci0/dev_${lamp}/service0023/char0024 org.bluez.GattCharacteristic1.ReadValue dict:string:variant:
	done
	echo -e '\n'
	echo "######################################"
	echo ">>>>>>>>>>>>> on/off <<<<<<<<<<<<<<<<<"
	echo "######################################"
	echo "/service0023/char0026"
	for lamp in ${array_lamps[@]}
	do
		dbus-send --print-reply --system --dest=org.bluez /org/bluez/hci0/dev_${lamp}/service0023/char0026 org.bluez.GattCharacteristic1.ReadValue dict:string:variant:
	done
	echo -e '\n'
	echo "######################################"
	echo ">>>>>>>>>>> brightness <<<<<<<<<<<<<<<"
	echo "######################################"
	echo "/service0023/char0029"
	for lamp in ${array_lamps[@]}
	do
		dbus-send --print-reply --system --dest=org.bluez /org/bluez/hci0/dev_${lamp}/service0023/char0029 org.bluez.GattCharacteristic1.ReadValue dict:string:variant:
	done
	echo -e '\n'
	echo "######################################"
	echo ">>>>>>>>>>>>> mired <<<<<<<<<<<<<<<<<<"
	echo "######################################"
	echo "/service0023/char002c"
	for lamp in ${array_lamps[@]}
	do
		dbus-send --print-reply --system --dest=org.bluez /org/bluez/hci0/dev_${lamp}/service0023/char002c org.bluez.GattCharacteristic1.ReadValue dict:string:variant:
	done
	echo -e '\n'
	echo "######################################"
	echo ">>>>>>>>>>>>>> color <<<<<<<<<<<<<<<<<"
	echo "######################################"
	echo "/service0023/char002f"
	for lamp in ${array_lamps[@]}
	do
		dbus-send --print-reply --system --dest=org.bluez /org/bluez/hci0/dev_${lamp}/service0023/char002f org.bluez.GattCharacteristic1.ReadValue dict:string:variant:
	done
	echo -e '\n'
	echo "######################################"
	echo ">> on/off, brightness, mired, color <<"
	echo "######################################"
	echo "/service0023/char0034"
	for lamp in ${array_lamps[@]}
	do
		dbus-send --print-reply --system --dest=org.bluez /org/bluez/hci0/dev_${lamp}/service0023/char0034 org.bluez.GattCharacteristic1.ReadValue dict:string:variant:
	done
	echo -e '\n'
	echo "######################################"
	echo ">>>>>>>>> transitiontime <<<<<<<<<<<<<"
	echo "######################################"
	echo "/service0023/char0037"
	for lamp in ${array_lamps[@]}
	do
		dbus-send --print-reply --system --dest=org.bluez /org/bluez/hci0/dev_${lamp}/service0023/char0037 org.bluez.GattCharacteristic1.ReadValue dict:string:variant:
	done
	echo -e '\n'
	echo "###################################################"
	echo "> AC_ON values : on/off, brightness, mired, color <"
	echo "###################################################"
	echo "/service0023/char0039"
	for lamp in ${array_lamps[@]}
	do
		dbus-send --print-reply --system --dest=org.bluez /org/bluez/hci0/dev_${lamp}/service0023/char0039 org.bluez.GattCharacteristic1.ReadValue dict:string:variant:
	done
	echo -e '\n'
	echo "######################################"
	echo ">>>>>>>>>>> ???  ??? <<<<<<<<<<<<<<<<<"
	echo "######################################"
	echo "/service003b/char003c"
	for lamp in ${array_lamps[@]}
	do
		dbus-send --print-reply --system --dest=org.bluez /org/bluez/hci0/dev_${lamp}/service003b/char003c org.bluez.GattCharacteristic1.ReadValue dict:string:variant:
	done
	echo -e '\n'
	echo "######################################"
	echo ">>>>>> send 02 00 posible <<<<<<<<<<<<"
	echo "######################################"
	echo "/service003b/char003e/desc0040"
	for lamp in ${array_lamps[@]}
	do
		dbus-send --print-reply --system --dest=org.bluez /org/bluez/hci0/dev_${lamp}/service003b/char003e/desc0040 org.bluez.GattDescriptor1.ReadValue dict:string:variant:
	done
	echo -e '\n'
	echo "######################################"
	echo ">>>>>>>>>>>> ???  ??? <<<<<<<<<<<<<<<<"
	echo "######################################"
	echo "/service003b/char0043"
	for lamp in ${array_lamps[@]}
	do
		dbus-send --print-reply --system --dest=org.bluez /org/bluez/hci0/dev_${lamp}/service003b/char0043 org.bluez.GattCharacteristic1.ReadValue dict:string:variant:
	done

}
